package modelo;
// Generated Mar 17, 2022 11:10:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private String metodoPago;
     private String nombreTitular;
     private Date fechaExpedicion;
     private String numeroTarjeta;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Pago() {
    }

	
    public Pago(int idPago, String metodoPago, String nombreTitular, Date fechaExpedicion, String numeroTarjeta) {
        this.idPago = idPago;
        this.metodoPago = metodoPago;
        this.nombreTitular = nombreTitular;
        this.fechaExpedicion = fechaExpedicion;
        this.numeroTarjeta = numeroTarjeta;
    }
    public Pago(int idPago, String metodoPago, String nombreTitular, Date fechaExpedicion, String numeroTarjeta, Set<Pedido> pedidos) {
       this.idPago = idPago;
       this.metodoPago = metodoPago;
       this.nombreTitular = nombreTitular;
       this.fechaExpedicion = fechaExpedicion;
       this.numeroTarjeta = numeroTarjeta;
       this.pedidos = pedidos;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public String getNombreTitular() {
        return this.nombreTitular;
    }
    
    public void setNombreTitular(String nombreTitular) {
        this.nombreTitular = nombreTitular;
    }
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


