package modelo;
// Generated Mar 17, 2022 11:10:28 PM by Hibernate Tools 4.3.1



/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private Pago pago;
     private Producto producto;
     private Usuario usuario;
     private String descriDireccion;
     private int codigoPostal;
     private String ciudad;
     private double total;
     
     private double subtotal;
     private double iva;


    public Pedido() {
        pago = new Pago();
        producto = new Producto();
        usuario = new Usuario();
    }

	
    public Pedido(int idPedido, String descriDireccion, int codigoPostal, String ciudad, double total) {
        this.idPedido = idPedido;
        this.descriDireccion = descriDireccion;
        this.codigoPostal = codigoPostal;
        this.ciudad = ciudad;
        this.total = total;
    }
    public Pedido(int idPedido, Pago pago, Producto producto, Usuario usuario, String descriDireccion, int codigoPostal, String ciudad, double total) {
       this.idPedido = idPedido;
       this.pago = pago;
       this.producto = producto;
       this.usuario = usuario;
       this.descriDireccion = descriDireccion;
       this.codigoPostal = codigoPostal;
       this.ciudad = ciudad;
       this.total = total;
    }
   
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescriDireccion() {
        return this.descriDireccion;
    }
    
    public void setDescriDireccion(String descriDireccion) {
        this.descriDireccion = descriDireccion;
    }
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    public double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public double getIva() {
        return iva;
    }

    public void setIva(double iva) {
        this.iva = iva;
    }




}


