package modelo;
// Generated Mar 17, 2022 11:10:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Categoria categoria;
     private Marca marca;
     private Proveedor proveedor;
     private String nombre;
     private String descripcion;
     private double precioUnitario;
     private byte[] imagen;
     private int stock;
     private String imagennombre;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Producto() {
        categoria = new Categoria();
        marca = new Marca();
        proveedor = new Proveedor();
    }

	
    public Producto(int idProducto, String nombre, String descripcion, double precioUnitario, int stock) {
        this.idProducto = idProducto;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precioUnitario = precioUnitario;
        this.stock = stock;
    }
    public Producto(int idProducto, Categoria categoria, Marca marca, Proveedor proveedor, String nombre, String descripcion, double precioUnitario, byte[] imagen, int stock, String imagennombre, Set<Pedido> pedidos) {
       this.idProducto = idProducto;
       this.categoria = categoria;
       this.marca = marca;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioUnitario = precioUnitario;
       this.imagen = imagen;
       this.stock = stock;
       this.imagennombre = imagennombre;
       this.pedidos = pedidos;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getImagennombre() {
        return this.imagennombre;
    }
    
    public void setImagennombre(String imagennombre) {
        this.imagennombre = imagennombre;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


