package modelo;
// Generated Mar 17, 2022 11:10:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String contacto;
     private String direccion;
     private String celular;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor, String nombre, String contacto, String direccion, String celular) {
        this.idProveedor = idProveedor;
        this.nombre = nombre;
        this.contacto = contacto;
        this.direccion = direccion;
        this.celular = celular;
    }
    public Proveedor(int idProveedor, String nombre, String contacto, String direccion, String celular, Set<Producto> productos) {
       this.idProveedor = idProveedor;
       this.nombre = nombre;
       this.contacto = contacto;
       this.direccion = direccion;
       this.celular = celular;
       this.productos = productos;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


